ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),  # Include the store app URLs
    path('users/', include(('users.urls', 'users'), namespace='users')), 
    path('schema-viewer/', include('schema_viewer.urls')) # Include the users app URLs
]

ecommerce/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # create all categories urls
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    # products
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    # cart
    path('cart/', views.CartDetailView.as_view(), name='cart_detail'),
    path('cart/add/<int:product_id>/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/remove/<int:product_id>/', views.RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('checkout/shipping', views.CheckoutView.as_view(), name='checkout_shipping'),
    path('checkout/payment', views.PaymentView.as_view(), name='checkout_payment'),
    path('payment/success/', views.PaymentSuccessView.as_view(), name='payment_success'),
    path('payment/failure/', views.PaymentFailureView.as_view(), name='payment_failure'),
    path('payment/pending/', views.PaymentPendingView.as_view(), name='payment_pending'),
    path('payment/webhook/', views.mercadopago_webhook, name='mercadopago_webhook'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    # Add the logout URL.
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.UserProfile.as_view(), name='user_profile'),
    path('addresses/create/', views.CreateUserAddress.as_view(), name='create_address'),
    path('addresses/', views.UserAddressesList.as_view(), name='user_addresses'),
    path('addresses/<int:pk>/update', views.UpdateAddress.as_view(), name='update_address'),
    path('addresses/<int:pk>/delete', views.DeleteAddress.as_view(), name='delete_address')
]

ecommerce/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.urls import reverse

class CustomUser(AbstractUser):

    def __str__(self):
        return f"{self.first_name} ({self.last_name})"
    
class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='addresses')
    address_line_1 = models.CharField("Address line 1", max_length=128)
    address_line_2 = models.CharField("Address line 2", max_length=128, blank=True, null=True)
    city = models.CharField("City", max_length=100)
    state = models.CharField("State / Province", max_length=100)
    postal_code = models.CharField("Postal Code", max_length=20)
    country = models.CharField("Country", max_length=100, default='Colombia')
    is_default = models.BooleanField("Default Address", default=False)

    def __str__(self):
        return f"{self.address_line_1}, {self.city}, {self.state} {self.postal_code}"
    
    def get_absolute_url(self):
        return reverse('user_addresses')
    
    class Meta:
        # Enforce that an address must be unique for a user.
        # An address is considered unique if the combination of all its fields 
        # (from address_line_1 to country) is unique for a given user.
        unique_together = ('user', 'address_line_1', 'address_line_2', 'city', 'state', 'postal_code', 'country') 
        verbose_name_plural = 'Addresses'

ecommerce/users/forms.py
from django import forms
from .models import CustomUser, Address

# Using forms.ModelForm provides more flexibility than UserCreationForm.
class CustomUserCreationForm(forms.ModelForm):
    # Explicitly define the password field with a PasswordInput widget 
    # to ensure the input is masked.
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        # Associate the form with the CustomUser model.
        model = CustomUser
        # Define the fields to be displayed in the form.
        fields = ['username', 'email', 'first_name', 'last_name', 'password']

    def save(self, commit=True):
        # Override the save method to handle password hashing.
        user = super().save(commit=False)
        # Use set_password() to securely hash the password 
        # before saving it to the database.
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user
        
class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['address_line_1', 'address_line_2', 'city', 'state', 'postal_code', 'country', 'is_default']
        widgets = {
            'address_line_1': forms.TextInput(attrs={'placeholder': 'Address Line 1'}),
            'address_line_2': forms.TextInput(attrs={'placeholder': 'Address Line 2'}),
            'city': forms.TextInput(attrs={'placeholder': 'City'}),
            'state': forms.TextInput(attrs={'placeholder': 'State'}),
            'postal_code': forms.TextInput(attrs={'placeholder': 'Postal Code'}),
            'country': forms.TextInput(attrs={'placeholder': 'Country'}),
        }

    def save(self, commit=True):
        # Override the save method to set the user field.
        address = super().save(commit=False)
        # Set the user to the currently logged-in user
        if address.is_default:
            # Ensure only one address can be default for the user
            # If the address is marked as default, unset the previous default address.
            # This ensures that the user can only have one default address.
            Address.objects.filter(user=address.user).update(is_default=False)

        if commit:
            address.save()
        return address

ecommerce/users/views.py
from django.db import IntegrityError
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from .models import Address  # Assuming you have an Address model defined
from .forms import CustomUserCreationForm, AddressForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Import Django's built-in authentication form and login/logout functions
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.views import View
from django.contrib.messages.views import SuccessMessageMixin

class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login') # Redirect to login page on successful registration

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form})

# This class handles the login process.
class LoginView(View):
    template_name = 'users/login.html'
    # Redirect to the homepage on successful login.
    success_url = reverse_lazy('store:index')

    def get(self, request, *args, **kwargs):
        # When a user visits the login page, display the authentication form.
        form = AuthenticationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        # When the user submits the form, process the credentials.
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # If the form is valid, authenticate the user.
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                # If authentication is successful, log the user in.
                login(request, user)
                return redirect(self.success_url)
        # If the form is invalid, re-render the page with the form and errors.
        return render(request, self.template_name, {'form': form})

# This class handles the logout process.
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        # When a user accesses this view, log them out.
        logout(request)
        # Redirect to the login page after logging out.
        return redirect(reverse_lazy('users:login'))

class UserProfile(View):
    template_name = 'users/user_profile.html'

    def get(self, request, *args, **kwargs):
        # Render the user's profile page.
        return render(request, self.template_name, {'user': request.user})

# USER ADDRESSES CRUD
class CreateUserAddress(LoginRequiredMixin, CreateView):
    model = Address
    form_class = AddressForm
    template_name = 'users/create_address.html'
    success_url = reverse_lazy('users:user_addresses')
    success_message = "Address added successfully"
    login_url = reverse_lazy('login')  # Redirect to login if not authenticated

    def form_valid(self, form):
        # Set the user to the currently logged-in user
        form.instance.user = self.request.user
        try:
            return super().form_valid(form)
        except IntegrityError:
            messages.error(self.request, 'You have already saved this address.')
            return self.form_invalid(form)
    

class UserAddressesList(ListView):
    model = Address  
    template_name = 'users/addresses.html'
    context_object_name = 'addresses'
    login_url = reverse_lazy('users:login')  # Redirect to login if not authenticated

    def get_queryset(self):
        # Filter addresses by the logged-in user
        return Address.objects.filter(user=self.request.user)
    
class UpdateAddress(LoginRequiredMixin, UpdateView):
    model = Address
    form_class = AddressForm
    template_name = 'users/update_address.html'
    success_url = reverse_lazy('users:user_addresses')
    success_message = "Address was updated successfully"
    login_url = reverse_lazy('users:login')  # Redirect to login if not authenticated

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

class DeleteAddress(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Address
    success_url = reverse_lazy('users:user_addresses')
    success_message = "Address was deleted successfully"
    login_url = reverse_lazy('users:login')  # Redirect to login if not authenticated

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

ecommerce/users/templates/users/addresses.html
{% extends "layout.html" %}

{% load static %}

{% block title %}
    <title>Addresses</title>
{% endblock %}

{% block content %}
    <h2>Manage Addresses</h2>
    <hr>

    {% if addresses %}
        <ul class="list-group">
            {% for address in addresses %}
                <li>{{address.address_line_1}}</li>
                <li>{{address.address_line_2}}</li>
                <li>{{address.city}}, {{address.state}} {{address.postal_code}}</li>
                <li>{{address.country}}</li>
                <li class="">
                    <a href="{% url 'users:update_address' pk=address.pk %}" class="btn btn-primary">Edit</a>
                    <form method="post" action="{% url 'users:delete_address' address.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </li>
            {% endfor %}
    {% else %}
        <p>No addresses available.</p>
    {% endif %}

    <hr>
    <a href="{% url 'users:create_address' %}" class="btn btn-outline-primary">Add address</a>

{% endblock %}

ecommerce/users/templates/users/create_address.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
    <h2>Create Address</h2>
    <hr>

    <form method="post" action="{% url 'users:create_address' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Address</button>
    </form>

    <hr>
    <a href="{% url 'users:user_addresses' %}">Back to Addresses</a>
    
{% endblock %}

ecommerce/users/templates/users/login.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Login
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Login to Your Account</h3>
                    </div>
                    <div class="card-body">
                        {% if form.errors %}
                            <div class="alert alert-danger">
                                Please correct the errors below.
                            </div>
                        {% endif %}
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary btn-block">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ecommerce/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
  Register
{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <h3 class="text-center">Create Your Account</h3>
          </div>
          <div class="card-body">
            {% if form.errors %}
              <div class="alert alert-danger">
                Please correct the errors below.
              </div>
            {% endif %}
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-row">
                <div class="form-group col-md-6">
                  {{ form.first_name.label_tag }}
                  {{ form.first_name }}
                </div>
                <div class="form-group col-md-6">
                  {{ form.last_name.label_tag }}
                  {{ form.last_name }}
                </div>
              </div>
              <div class="form-group">
                {{ form.email.label_tag }}
                {{ form.email }}
              </div>
              <div class="form-group">
                {{ form.phone_number.label_tag }}
                {{ form.phone_number }}
              </div>
              <div class="form-group">
                {{ form.address_line_1.label_tag }}
                {{ form.address_line_1 }}
              </div>
              <div class="form-group">
                {{ form.address_line_2.label_tag }}
                {{ form.address_line_2 }}
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  {{ form.city.label_tag }}
                  {{ form.city }}
                </div>
                <div class="form-group col-md-4">
                  {{ form.state_province.label_tag }}
                  {{ form.state_province }}
                </div>
                <div class="form-group col-md-2">
                  {{ form.zip_postal_code.label_tag }}
                  {{ form.zip_postal_code }}
                </div>
              </div>
              <div class="form-group">
                {{ form.country.label_tag }}
                {{ form.country }}
              </div>
              <div class="form-group">
                {{ form.profile_picture.label_tag }}
                {{ form.profile_picture }}
              </div>
              <div class="form-group">
                {{ form.password.label_tag }}
                {{ form.password }}
              </div>
              <div class="form-group">
                {{ form.password2.label_tag }}
                {{ form.password2 }}
              </div>
              <button type="submit" class="btn btn-primary btn-block">Register</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ecommerce/users/templates/users/update_address.html
{% extends 'layout.html' %}

{% load static %}<!-- Load the custom filter for dictionary access -->

{% block content %}
    <div class="address-form">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
    <br>
    <div class="delete-form">
        <form method="post" action="{% url 'users:delete_address' address.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete Address</button>
        </form>
    </div>

{% endblock %}

ecommerce/users/templates/users/user_profile.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
    <title>User profile</title>
{% endblock %}

{% block content %}

    <div class="user-card">
        <h4>{{user.first_name}} {{user.last_name}}</h4>
        <h6>{{user.username}}</h6>
        <h6>{{user.email}}</h6>
    </div>

    <div class="option-cards">
        <a href="#" class="card">
            <h5>My Orders</h5>
            <p>View your past orders.</p>
        </a>

        <a href="#" class="card">
            <h5>Account</h5>
            <p>Update your personal information</p>
        </a>

        <a href="#" class="card">
            <h5>Wishlist</h5>
            <p>View items you have saved for later.</p>
        </a>

        <a href="" class="card">
            <h5>Payment information</h5>
            <p>Manage your payment methods.</p>
        </a>
        <a href="{% url 'users:user_addresses' %}" class="card">
            <h5>Addresses</h5>
            <p>Manage your addresses.</p>
        </a>    
    </div>
    
    <hr>
    <a href="">Delete account</a>


{% endblock %}