ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),  # Include the store app URLs
    path('users/', include(('users.urls', 'users'), namespace='users')), 
    path('schema-viewer/', include('schema_viewer.urls')) # Include the users app URLs
]

ecommerce/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # create all categories urls
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    # products
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    # cart
    path('cart/', views.CartDetailView.as_view(), name='cart_detail'),
    path('cart/add/<int:product_id>/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/remove/<int:product_id>/', views.RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('checkout/shipping', views.CheckoutView.as_view(), name='checkout_shipping'),
    path('checkout/payment', views.PaymentView.as_view(), name='checkout_payment'),
    path('payment/success/', views.PaymentSuccessView.as_view(), name='payment_success'),
    path('payment/failure/', views.PaymentFailureView.as_view(), name='payment_failure'),
    path('payment/pending/', views.PaymentPendingView.as_view(), name='payment_pending'),
    path('payment/webhook/', views.mercadopago_webhook, name='mercadopago_webhook'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    # Add the logout URL.
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.UserProfile.as_view(), name='user_profile'),
    path('addresses/create/', views.CreateUserAddress.as_view(), name='create_address'),
    path('addresses/', views.UserAddressesList.as_view(), name='user_addresses'),
    path('addresses/<int:pk>/update', views.UpdateAddress.as_view(), name='update_address'),
    path('addresses/<int:pk>/delete', views.DeleteAddress.as_view(), name='delete_address')
]

ecommerce/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'store:index' %}">My Shop</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'users:user_profile' %}">{{user.username}}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'store:cart_detail' %}">Cart</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% include 'includes/messages.html' %}
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>